### ISSUE TITLE
Modify the admin login page 

### ISSUE THREAD

**Issue by Sibam-Paul** [bishalde/Shrinkk#28]
**Issue Description**
Saw that admin page is not modified nicely 

Screenshots
![admin page](https://github.com/bishalde/Shrinkk/assets/158052549/eef8c6cc-9e15-4f10-8f5e-4484753cbb8e)

**Proposed changes**
I can modify the admin login page with CSS  

**So please assign me this project under GSSOC'23**

_Please give necessary tags for the  GSSOC'24_

**Comment by Kulashekar01** [comment]
I would like to work on this project under GsSoc'24 please assign me this

**Comment by palayushi293** [comment]
i would like to work on this issue ,, provide you the best
Waiting for your response
