### ISSUE TITLE
[Bug] Generating a link even if the input is empty.

### ISSUE THREAD

**Issue by TusharKumarChopra** [bishalde/Shrinkk#7]
A link is being generated even if the input is empty and that takes us to a "page not found" page.
Please assign this issue to me, I would like to resolve this.

**Comment by bishalde** [comment]
Thanyou @TusharKumarChopra for finding this issue.
Sure, you can proceed with it.!


```bash
git fetch origin
git checkout empty-input
```
I have created a new branch, push the changes in that branch!

And feel free to give this Repository a STAR⭐ and follow back 😊.

**Comment by bishalde** [comment]
Thanyou @TusharKumarChopra for finding this issue.
Sure, you can proceed with it.!


```bash
git fetch origin
git checkout empty-input
```
I have created a new branch, push the changes in that branch!

And feel free to give this Repository a STAR⭐ and follow back 😊.

**Comment by TusharKumarChopra** [comment]
@bishalde Please assign Level for gssoc.
