### ISSUE TITLE
Highlighting the buttons on Nav Bar

### ISSUE THREAD

**Issue by kdanjana** [bishalde/Shrinkk#8]
GSSOC24
I want to highlight the buttons on the navbar when cursor is pointing at them. like this, 
<img width="881" alt="Screenshot 2024-05-09 095454" src="https://github.com/bishalde/Shrinkk/assets/103878831/415fb33e-3f6e-48c0-9808-a84c739b8ede">

**Comment by bishalde** [comment]
Thanyou @kdanjana for finding this issue.
Sure, you can proceed with it.!

```bash
git fetch origin
git checkout navbar-buttons
```
I have created a new branch, push the changes in that branch!

And feel free to give this Repository a STAR⭐ and follow back 😊.
