### ISSUE TITLE
Copy Links not working in Shorten page.

### ISSUE THREAD

**Issue by kdanjana** [bishalde/Shrinkk#9]
GSSOC
In the shorten page, you cannot copy the shorten link or original link when you press the buttons. I would like to add that functionality to those button using JavaScript.
<img width="361" alt="stgdsg" src="https://github.com/bishalde/Shrinkk/assets/103878831/f56d334d-ef81-42f7-ac5e-d0b93b6dd68a">

**Comment by bishalde** [comment]
Thanyou @kdanjana  for finding this issue.
Sure, you can proceed with it.!

```bash
git fetch origin
git checkout links
```
I have created a new branch, push the changes in that branch!

And feel free to give this Repository a STAR⭐ and follow back 😊.

**Comment by bishalde** [comment]
Great!
